### ISSUE TITLE
AA3000+ DSP3210 tests and demos fail with ReSDMAC

### ISSUE THREAD

**Issue by trixster1979** [mbtaylor1982/ReSDMAC#14]
Set up: Amiga AA3000+ with BFG9060 running at 100MHz, 128MB of accelerator  FastRam, 16MB motherboard FastRam, 2MB ChipRam, Freeway Pro for some OS modules and libraries. 
OS3.1.4 install with 3.1.4 kickstart roms, using Acard 7720UW via IDE to SD adapter

Reported Issue occurs with SCSI set to async or sync.
Reported Issue occurs with motherboard 030 and with BFG9060 installed.

DSP ATFs use the following timings, broadly stable with 030 and BFG using C= SDMAC-02: U122 5, U123 10, U124 5, U701 15
—————

With ReSDMAC firmwares 0.4 and 0.6 the AA3000+’s DSP3210 fails to run Wrangler’s WMHB DSP demo or his Mandel_DSP program. Both will crash (hard lock, no guru) immediately when launched. 

A10001986’s DSP3210devtest will return ‘execution timeouts in int2 / int6 tests’ once the test summary is displayed. All other tests complete without errors. 

Wrangler’s adaptation of WhichAmiga will correctly detect the DSP, and A10001986’s version of Mandel_DSP will work correctly looping between fpu and dsp continuously without crashing. 

https://aminet.net/package/driver/other/dsp3210
https://github.com/realA10001986/AmigaDSP3210
http://aminet.net/package/demo/aga/WhatMightHaveBeen.lha
https://aminet.net/package/gfx/fract/mandel_dsp

![IMG_4455](https://github.com/user-attachments/assets/71901d18-7fb4-4996-9e8d-e5fbcf75c44d)

**Comment by trixster1979** [comment]
V0.7fw - no improvement to WMHB or Wrangler’s version of mandel_dsp. Machine locks up when either program attempts to use the DSP.

dsp3210devtest still reports Int6 sync and async errors 
![Uploading IMG_4652.jpeg…]()

**Comment by trixster1979** [comment]
![IMG_4652](https://github.com/user-attachments/assets/8d5a15db-232e-43d3-8270-277484371b16)

**Comment by mbtaylor1982** [comment]
@Wrangler491 Is it fair to say that the issue appears to be that the DSP not signaling and INT6 after being sent code that should trigger it?

**Comment by mbtaylor1982** [comment]
I've changed the code so it will not respond at all to address `$00DD005C` l don't know if this is the right thing to do as  I'm not sure if a REV4 SDMAC is required to read the data from the DSP at this address. I tried to look at the code for that GALS and i don't see where it is decoding the read address so this fix may be in entirely the wrong direction.

**Comment by mbtaylor1982** [comment]
@trixster1979 try the build from here https://github.com/mbtaylor1982/ReSDMAC/actions/runs/11430166320 and see if it works any better with the dsp.

**Comment by trixster1979** [comment]
> @trixster1979 try the build from here https://github.com/mbtaylor1982/ReSDMAC/actions/runs/11430166320 and see if it works any better with the dsp.

With this build i get the following:
motherboard 030 - I can see my scsi hdd in the early startup menu but booting causes an 80000008 guru and then a reboot loop. There is an inital flicker from the machine's scsi led but it wont access scsi thereafter.

BFG9060 - the scsi hdd is not seen at all in the early boot menu. The machine won't boot to a kickstart disk prompt.

Tested with no scsi hdd, using a floppy disk with sdmac, dsp3210devtest and WMHB demo. SDMAC sees the ReSDMAC, dsp3210devtest will not start performing tests (fails at the first test initiation) and WMBH demo crashes when the demo starts.

**Comment by Wrangler491** [comment]
_Is it fair to say that the issue appears to be that the DSP not signaling an INT6 after being sent code that should trigger it?_
No, my software doesn't operate by the DSP interrupting the CPU (and especially not using INT6), so this is a coincidence.

**Comment by Wrangler491** [comment]
The issue with DSP programs is down to a problem reading the DSP control register at 0xDD005C.  The bits of this register are connected to SDMAC "AP" port, where AP_0 is pin 58 and AP_7 is pin 74.  Writing to the control register (at address 0xDD0080) is fine.  Changing the programs to avoid reading the register fixes all the problems.

**Comment by mbtaylor1982** [comment]
@trixster1979 @Wrangler491  can you try the build from here https://github.com/mbtaylor1982/ReSDMAC/actions/runs/11534066708 it may work without modifying your demo @Wrangler491

**Comment by trixster1979** [comment]
tested. no dice sadly. both the original WMHB demo and the original mandel_dsp crash as before. as expected, the modified versions still work ok.

**Comment by mbtaylor1982** [comment]
latest build for testing https://github.com/mbtaylor1982/ReSDMAC/actions/runs/11542299012

**Comment by trixster1979** [comment]
This resolves the issue! 

All original DSP test programs now run without having to be patched.

**Comment by realA10001986** [comment]
> I've changed the code so it will not respond at all to address `$00DD005C` l don't know if this is the right thing to do as I'm not sure if a REV4 SDMAC is required to read the data from the DSP at this address. I tried to look at the code for that GALS and i don't see where it is decoding the read address so this fix may be in entirely the wrong direction.

$dd005c is mostly the DSP's BIOC register mapped to the SDMAC's AP_0:7 and as such supposed to mostly mirror what is written to $dd0080 (or set by the DSP). Writing to $dd0080 is handled by the U124 GAL. 

BIOC contains interrupt masking, host and DSP interrupt triggering, reset. Since the software needs to set/clear individual bits, it is supposed to read from $dd005c, clear/set bits, and write back to $dd0080.

The dsp3210.resource tests the hardware by writing to $dd0080 and checking if the contents of $dd005c makes sense:

detectDMAC4:
  lea.l $dd005c,a1
  lea.l ($dd0080-$dd005c)(a1),a0
  move.b #$7f,(a0)  ; Put DSP in RESET, set  INT6/INT2 masking bits
  moveq.l #50,d0
  bsr delayloop
  move.l (a1),d0    ; Read from $dd005c
  andi.b #$b0,d0 
  cmpi.b #$30,d0  ; check if INT6/INT2 masking matches written data
  bne.s 1$              ; if not, bail (and use shadow instead of hardware register)
  move.b #$4f,(a0)    ; clear  INT6/INT2 masking bits
  moveq.l #50,d0
  bsr delayloop
  move.l (a1),d0
  andi.b #$30,d0  ; check if INT6/INT2 masking matches written data
  bne.s 1$            ; if not, bail (and use shadow instead of hardware register)
  moveq.l #-1,d0
  rts
1$:
  moveq.l #0,d0
  rts

If the data does not make sense (ie the masking bits aren't correct after writing them to $dd0080), the driver uses a stored write-shadow instead of reading from $dd0050. This works fine, so $dd005c isn't really required, but if it is implemented, it really needs to contain valid data.

Hope this helps.

**Comment by mbtaylor1982** [comment]
Thanks for the additional info @realA10001986, this is consistent with my understanding. @trixster1979 confirmed this issue has been resolved and DSP code can now run happily with the ReSDMAC installed.
